### ISSUE TITLE
Make pane resizable

### ISSUE THREAD

**Issue by lardissone** [josa42/atom-blame#1]
I use large fonts and makes it useless.

Example:
![documents_py_-__users_leandroardissone_workspace_projects_treat-2-target_-_atom](https://cloud.githubusercontent.com/assets/59826/8571487/8ef31f18-255d-11e5-98a7-fd3bc24813b2.png)

**Comment by josa42** [comment]
@lardissone The gutter is now resizable. You can also change the default width in the settings.

**Comment by lardissone** [comment]
@josa42 awesome!
