### ISSUE TITLE
'Default Width' config invalid in Atom 1.13.x

### ISSUE THREAD

**Issue by mattaschmann** [josa42/atom-blame#28]
I'm using Atom Beta 1.13-beta4.  They have decided to remove the shadow dom in this version, rending this code invalid:

```
sheet.innerHTML = `
      atom-text-editor::shadow .gutter[gutter-name="blame"] {
        width: ${this.state.width}px;
      }
    `
```

It looks like this, regardless of setting.

![image](https://cloud.githubusercontent.com/assets/13682706/20448201/1f1e46dc-ada0-11e6-9da8-60b8aa8a9b2d.png)

I can override this for now using this in my stylesheet:

```
// Customization for atom-blame plugin
atom-text-editor {
  .gutter[gutter-name="blame"] .custom-decorations {
    width: 350px;
  }
}
```

**Comment by afc163** [comment]
+1
