### ISSUE TITLE
Show each commit in its own colour.

### ISSUE THREAD

**Issue by sboekhoff** [josa42/atom-blame#36]
As a user I'd like to be supported at seeing which lines were changed in the same commit.
Therefore it would be great to show the background of each blame-line in a colour that is specific for the commit.
Currently the blame plugin only alternates between classes `blame-odd` and `blame-even`.
A possible solution would be to use the first 6 character of the commit hash as RGB colours for an `X %` transparent background colour.

**Comment by sboekhoff** [comment]
@josa42: It just noticed that your branch [experimental-colors](https://github.com/josa42/atom-blame/compare/experimental-colors) goes into that direction.

**Comment by josa42** [comment]
<img width="701" alt="screen shot 2017-05-23 at 11 59 17" src="https://cloud.githubusercontent.com/assets/423234/26349176/4fa0b208-3faf-11e7-9c58-6bfe14646abd.png">

The latest release adds a color to the left border of the gutter.
