### ISSUE TITLE
Click through to a commit URL

### ISSUE THREAD

**Issue by johnbillion** [josa42/atom-blame#40]
Browsing the code for this package, it appears there is support for clicking through to view the corresponding commit at a URL, but I can't find a way to trigger this.

Does this functionality still work? Where should I click to open the commit URL in my browser?

I'm using Atom beta 1.19.0.

Thanks in advance.

**Comment by josa42** [comment]
You would click this icon:

<img width="151" alt="contact_php_ _lib_controlers_ ___projects_intern-ligadigital-website-2017" src="https://user-images.githubusercontent.com/423234/28967634-5f3a9a20-791c-11e7-8e10-61304223c7ef.png">

**Comment by johnbillion** [comment]
Thanks! That works.

I hadn't spotted those links. They're very hard to see as they are the same colour as the text below. Maybe they could be styles more like buttons so they stand out more.

Thanks for your work on this package - it's really helpful!
