### ISSUE TITLE
"Blame: Toggle" while tooltip is open, leaves the tooltips open and will not go away even when navigating to new files

### ISSUE THREAD

**Issue by jkieley** [josa42/atom-blame#6]
Performing the "Blame: Toggle"  command. 
While the commit tooltip is open, leaves the tooltips open and will not go away even when navigating to new files. 
![Image of Issue](http://jkieley.github.io/tooltip_wont_go_away.png)

**Comment by josa42** [comment]
I can't reproduce this. ~~And your screenshot gone.~~ Can your provide me more information on what exactly you are doing?

I do this:
1. Open 2 Files.
2. Hover over a commit. The tooltip opens.
3. Switch tab. The tooltip disappears

![screen-recording](https://cloud.githubusercontent.com/assets/423234/9234603/12c26d1a-413a-11e5-9f91-d361e06d2f90.gif)

**Comment by jkieley** [comment]
sorry for the low quality gif, I also created a video. 
![what happened gif](http://zippy.gfycat.com/FatalIckyLabradorretriever.gif)
here is full screen video:
http://screencast.com/t/FOtF6mY7pBAW

**Comment by josa42** [comment]
Thanks. Now i got it ;-)
